# Generated by Django 4.1.7 on 2023-03-22 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizzeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizzeria_name', models.CharField(max_length=200)),
                ('street', models.CharField(blank=True, max_length=400)),
                ('city', models.CharField(blank=True, max_length=400)),
                ('description', models.TextField(blank=True)),
                ('logo_image', models.ImageField(blank=True, upload_to='pizzeriaImages')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
